### ISSUE TITLE
Font-awesome icons not hidden on firefox

### ISSUE THREAD

**Issue by Seb33300** [nnattawat/flip#31] opened 2015-07-16 10:00 UTC
Hello,

I think it could be a firefox bug: when using font awesome icon in the front div, the icon still be visible when the div is flipped if background is transparent.

**Comment by Download** [comment] 2015-07-16 10:35
Can you create a [JS Fiddle](https://jsfiddle.net/) of it maybe?

**Comment by Seb33300** [comment] 2015-07-16 12:11
https://jsfiddle.net/g3dsksm5/

**Comment by Download** [comment] 2015-07-16 12:36
Thank you! Very clear example

**Comment by Download** [comment] 2015-07-16 12:54
I notice that Font Awesome adds this style rule:

    transform: translate(0px, 0px);

If I remove it then the issue disappears.
It's a bit of a strange style rule wouldn't you say?

I wonder if this is an issue with flip or with font awesome? That rule looks like it's a fix for something... Why else would they `translate(0px, 0px)`? This should normally have no effect whatsoever I think...

As I understand you are running into this issue I would like to ask you to see if the people from Font Awesome have something to say about this? I'm willing to (help you) fix this in Flip but I don't really feel like adding Font Awesome specific styling rules to Flip....

**Comment by Download** [comment] 2015-07-16 12:57
See [this fixed version of the fiddle](https://jsfiddle.net/g3dsksm5/1/)

**Comment by Seb33300** [comment] 2015-07-16 13:25
I think it's a firefox bug. Others browsers do not have this issue.
And it's the container div which is flipped, not the icon.

**Comment by Download** [comment] 2015-07-16 13:38
Yes this could well be. 

So what do you propose going forward?

**Comment by JemarJones** [comment] 2015-07-17 04:14
Indeed this is some unusual styling from fa, but i played around a little bit and all we have to do is the apply the following style to prevent any weird code like this causing this issue:
```css
    .back > *, .front > *{
        backface-visibility: hidden;
    }
```
see the updated fiddle here https://jsfiddle.net/g3dsksm5/4/.

Of course we should do this with our jQuery rather than hardcoding selectors, but that's the idea. 

This way we can prevent any unusual styling such as this and don't have to hardcode a fa specific exception.

**Comment by JemarJones** [comment] 2015-07-17 11:28
So fa has confirmed that this is an issue of theirs and will be fixed in the next release https://github.com/FortAwesome/Font-Awesome/commit/0810752c860b540e5f70a9d5de75e1543b75fa62#commitcomment-12221926. Still, I'm not sure what sort of issues not hiding the backface of all children elements might cause in the future. So I'm not opposed to adding this fix so long as it doesn't somehow cause problems itself.

**Comment by Seb33300** [comment] 2015-07-17 14:30
Why is this plugin not hiding (display: none) the hidden block instead of just change backface-visibility to hidden?

**Comment by JemarJones** [comment] 2015-07-17 15:10
It's cleaner and the same thing can be achieved if used correctly.

**Comment by Download** [comment] 2015-07-17 15:41
@Seb33300 Actually, using `display:none` is harder than you might think. The element becomes visible during the flip animation... So you would have to toggle `display:none` on and off halfway the animation.

The advantage of `backface-visibility: hidden` is that the 3D engine handles it. And that 'knows' exactly when the face becomes visible.

**Comment by JemarJones** [comment] 2015-07-17 22:44
@Download So do you agree with adding my change?

**Comment by Download** [comment] 2015-07-19 17:41
@JemarJones Sorry for the late response. Yes I think you found a good generic solution.

**Comment by Seb33300** [comment] 2015-07-23 07:45
I can reproduce a similar problem which only occurs on Google Chrome while adding this plugin in flip divs: http://tympanus.net/Development/ResponsiveMultiLevelMenu/

CSS code given by @JemarJones also solve this bu on Google Chrome.

Can you also take into account that front/back selectors can be changed?

**Comment by JemarJones** [comment] 2015-07-23 11:45
Yes it seems that they've got some conflicting transforms in there as well. Does that plugin behave as expected? I'd imagine that plugin wouldn't work too well inside of a flipped element in general? 

We'll just use some JavaScript, you can take a look at that last commit that referenced this above. I'll update the release with this fix later today most likely.

**Comment by Seb33300** [comment] 2015-07-23 11:48
I have no other problem using this inside a flipped element except some flipped element which still visible when on their back side. But solved with your CSS

**Comment by JemarJones** [comment] 2015-07-23 16:29
Hmm okay, that's interesting.

**Comment by JemarJones** [comment] 2015-07-23 23:28
This is now in the release.

**Closed by JemarJones** 2015-07-23 23:28 UTC

**Comment by Download** [comment] 2015-07-31 16:44
The Font Awesome bug has also been fixed:
https://github.com/FortAwesome/Font-Awesome/issues/6023
